version: '3.4'

services:
  dtn.web:
    image: ${DOCKER_REGISTRY-}dtnweb
    volumes:
    - /var/run:/var/run
    - ${USERPROFILE}/.aws/:/root/.aws
    environment:
      - AWS_REGION=ca-central-1
      - AWS_PROFILE=default
    build:
      context: .
      dockerfile: DTN.Web/Dockerfile
